spring:
  application:
    name: demo-app
ai:
  swagger:
    helper:
      enabled: true
      api-key: ${API_KEY}
      model-name: openrouter/aurora-alpha
      temperature: 0.8
      options:
        frequency_penalty: 2.0
        repeat_penalty: 1.1

logging:
  level:
    root: info