spring:
  application:
    name: demo-app
  ai:
    openai:
      api-key: ${API_KEY}
      chat:
        base-url: https://openrouter.ai/api
        options:
          model: openrouter/aurora-alpha
          temperature: 0.8
          frequencyPenalty: 2.0

devtools:
  ai:
    swagger:
      enabled: true
      mode: ai

logging:
  level:
    root: info